name: hanskainz
favicon: null
layout_spectrum: 0.26243
typography_spectrum: 0.22149
title: Hans Kainz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1418169-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#141c1e'
    - '#e0e1e5'
    - '#fbfcf7'
    - '#393937'
    - '#6a6663'
  brandStrength: 0.75
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
