name: hanskainz
favicon: null
layout_spectrum: 0.26243
typography_spectrum: 0.22149
title: Hans Kainz
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-1418169-7
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#264e8b'
    - '#7f96ba'
    - '#680630'
    - '#e37a7a'
  brandStrength: 0.8799439372960478
  lightness: 0.46274466160684824
  saturation: 0.4089025624562055
  rhythmicContrast: 0.4098752192221582
purpose: []
